### ISSUE TITLE
Why doesn't my toaster have a spaghetti setting?

### ISSUE THREAD

**Issue by gcflames5** [Zyneak/Stormcloud#1]
I bought [this toaster](http://s3-ec.buzzfed.com/static/enhanced/terminal05/2012/10/4/15/enhanced-buzz-15014-1349380406-5.jpg) however when I put the spaghetti in the toaster and then went to bed, the spaghetti was on fire and my dinner was ruined. 

Please send me a spaghetti-friendly toaster please. Thank you.

**Comment by skipperguy12** [comment]
I had a similar issue. My support ticket was completely ignored by this garbage service, and I didn't have macaroni that night. You can probably understand how devastated I was.

**Comment by NathanTheBook** [comment]
These faulty toasters caused the death of my lovely grann. All she wanted was some nice chicken Alfredo. I guess she'll be eating eorh Jesus tonight. Expect a lawsuit notice In the post sometime this week.

**Comment by Zyneak** [comment]
It's on it's way. 

Thanks for bringing this to my attention.

**Comment by gcflames5** [comment]
reopen pls I am still
